name: Main workflow
on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make scripts executable
        run: chmod +x ci/*.sh
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload code artifact
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
          include-hidden-files: true

  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Optional: download build artifact if lint rules need build outputs
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: micronaut-app
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .

      - name: Debug files
        run: ls -R .

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u $OWNER --password-stdin

      - name: Build Docker image
        run: docker build -f app/Dockerfile -t $REGISTRY/$OWNER/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $REGISTRY/$OWNER/$IMAGE_NAME:latest
