name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: ex to build-app
        run: chmod +x ci/build-app.sh
      - name: Build application
        run: ci/build-app.sh
      - name: ex to unit-test-app.sh
        run: chmod +x ci/unit-test-app.sh
      - name: Test  
        run: ci/unit-test-app.sh
      
